service: recipe-runner

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2
  environment:
    DB_HOSTNAME: ${ssm:/db_hostname~true}
    DB_USERNAME: ${ssm:/db_username~true}
    DB_PASSWORD: ${ssm:/db_password~true}
    DB_DATABASE: recipe-runner

functions:
  fetch-recipe:
    handler: src/handler.fetchRecipe
    events:
      - http:
          path: recipes/{recipeId}
          method: get
  fetch-recipes:
    handler: src/handler.fetchRecipes
    events:
      - http:
          path: recipes
          method: get
  delete-recipe:
    handler: src/handler.deleteRecipe
    events:
      - http:
          path: recipes/{recipeId}
          method: delete
